### ISSUE TITLE
Immersion conflict with certain dialogs

### ISSUE THREAD

**Issue by Chamlotte** [N0ich/dialogkey-DF#16] opened 2022-11-27 21:30 UTC
With both this and Immersion, some dialogs leave what i would just call a ghost dialog box that dialogkey tries to interact with.

The easiest test was just a transmogrifier. Talk to them, hit space(or 1, to select that dialog option), and now every time you hit space DK is trying to hit a dialog box that isn't there anymore, even after leaving the transmog. Opening up another dialog clears this issue.

No lua error is produced. 

https://i.imgur.com/uaLCDCS.mp4

**Comment by FuriousProgrammer** [comment] 2022-11-27 23:00
Now that *is* strange. It looks like it's trying to click a button on a Gossip panel, which means that the Gossip panel `:IsVisible()` is returning true, despite it clearly not being Visible.

I'll look into what Immersion is doing to cause this and figure out a workaround.

I can't actually test anything for a couple hours, so if you see this quicklike please let me know if pressing Escape (or whatever your keybind for closing menus is if you've changed it!) disabled the "ghost" Gossip panel.

**Comment by Chamlotte** [comment] 2022-11-28 00:06
Trying to hit escape just gives the normal escape menu, and mashing space even then looks like it's trying to hit a dialog option.

**Comment by FuriousProgrammer** [comment] 2022-11-28 00:39
Anima deposit, you mean?

I'll take a look once I get home if Immersion is causing this to occur or if that's part of DialogKey itself.

In any case, Immersion has its own options for keybinds for quest and gossip stuff, I presume you personally just want DialogKey for the StaticPopup stuff (e.g. release spirit, accept rez, group invite etc.)?

I ask because it's simpler to disable DialogKey stuff for the non-popups than to insert a workaround for specifically what Immersion does that is breaking DialogKey.

**Comment by Chamlotte** [comment] 2022-11-28 03:20
Oh, yeah, i use it mainly for StaticPopup stuff, since immersion already hooks into the regular quest/npc windows.

**Comment by N0ich** [comment] 2022-11-28 15:38
Hello,
Are you sure you are using the latest version of dialogkey? Im trying to reproduce this with the latest version and I can't, on neither the transmogrifier nor the anima collector. I remember fixing something like that at some point so i'd assume you don't use the latest version.
Otherwise it's a bug between Immersion and DK, in which case you should probably adapt the addon to just interact with Popups

**Comment by Chamlotte** [comment] 2022-11-28 18:35
I was using 1.3.5b, which is what i found over on curse, but now i see a 1.4.0b to update to. Sure didn't see it yesterday!

**Comment by smbody-mipt** [comment] 2022-11-29 19:37
Also appears to still be happening even if gossip option is disabled in DK, even after interface reload - maybe it hooks by default regardless of the option and still causes the issue.

**Comment by FuriousProgrammer** [comment] 2022-12-13 03:59
Testing this just now with the most recent version of Immersion with their default settings (and a minor fix to make sure the gossip ordering is *always* correct in DK), and I cannot reproduce this behavior.

I'll add a chat message saying that Immersion is known to conflict with DialogKey, but as best I can figure this issue is resolved by some change made recently to Immersion itself.

**Closed** 2022-12-13 04:08 UTC
Labels: bug
